// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LuminarTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void luminar() {
    driver.get("https://www.luminartechnolab.com/");
    driver.findElement(By.cssSelector(".nav-item:nth-child(2) > .nav-link > a")).click();
    driver.findElement(By.cssSelector(".courses-paragraph-button")).click();
    driver.findElement(By.id("fullName")).click();
    driver.findElement(By.id("fullName")).sendKeys("sahal");
    driver.findElement(By.id("contact-number")).click();
    driver.findElement(By.id("contact-number")).sendKeys("8138877120");
    driver.findElement(By.id("email-id")).click();
    driver.findElement(By.id("email-id")).sendKeys("sahalsalu286@gmail.com");
    driver.findElement(By.id("district")).click();
    driver.findElement(By.id("district")).sendKeys("pavarty");
  }
}
